### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Aracki** [DecenterApps/EthGame#1]
When I try to start app from `/server` with `npm start` I got the following error: 

> Error: Cannot find module '../solidity/build/contracts/GameManager'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raca/EthGame/server/game-manager.js:5:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by yippee-ki-yay** [comment]
Hi @Aracki thanks for looking at the code base, this is a project which is currently in the 'prototype' phase and isn't functional and will change a lot in the next month.

If you really want to try it, to fix your problem you go to /solidity and run 'truffle develop' and then 'migrate' (you'll need to have truffle 4 installed)

**Comment by Aracki** [comment]
Thanks. I managed to start the game.
